Document: epics-seq
Title: Debian epics-seq Manual
Author: <insert document author here>
Abstract: This manual describes what epics-seq is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/epics-seq/epics-seq.sgml.gz

Format: postscript
Files: /usr/share/doc/epics-seq/epics-seq.ps.gz

Format: text
Files: /usr/share/doc/epics-seq/epics-seq.text.gz

Format: HTML
Index: /usr/share/doc/epics-seq/html/index.html
Files: /usr/share/doc/epics-seq/html/*.html
